[package]
name = "school-mis"
version = "5.0.0"
description = "School MIS — Modern Desktop"
authors = []
license = ""
repository = ""
default-run = "school-mis"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "school_mis_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri            = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde            = { version = "1", features = ["derive"] }
serde_json       = "1"

[profile.release]
codegen-units = 1
lto           = true
opt-level     = "s"
panic         = "abort"
strip         = true
