"""PDF / print-preview export using Qt's built-in print support (no extra libs)."""

import datetime
from PyQt6.QtPrintSupport import QPrinter, QPrintPreviewDialog
from PyQt6.QtGui import QTextDocument
from PyQt6.QtCore import QMarginsF


def _school_name() -> str:
    try:
        from database.db import get_config
        return get_config("school_name") or "School Management System"
    except Exception:
        return "School Management System"


def _page_html(title: str, body: str) -> str:
    school = _school_name()
    now = datetime.datetime.now().strftime("%d %B %Y  %H:%M")
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body{{font-family:Arial,Helvetica,sans-serif;font-size:10.5pt;color:#111;margin:0;}}
  .hd{{text-align:center;border-bottom:2px solid #111;padding-bottom:10px;margin-bottom:14px;}}
  .hd h1{{font-size:16pt;margin:0 0 2px 0;}}
  .hd .sub{{font-size:9.5pt;color:#555;}}
  .kv{{margin:5px 0;line-height:1.5;}}
  .kv b{{display:inline-block;min-width:160px;color:#374151;}}
  hr.thin{{border:none;border-top:1px solid #D1D5DB;margin:10px 0;}}
  table{{width:100%;border-collapse:collapse;margin-top:6px;font-size:9.5pt;}}
  th{{background:#F3F4F6;font-weight:700;padding:6px 8px;text-align:left;
      border:1px solid #D1D5DB;}}
  td{{padding:5px 8px;border:1px solid #E5E7EB;vertical-align:top;}}
  tr:nth-child(even){{background:#F9FAFB;}}
  .red{{color:#991B1B;}} .green{{color:#065F46;}} .orange{{color:#92400E;}}
  .bold{{font-weight:700;}}
  .footer{{margin-top:18px;border-top:1px solid #E5E7EB;padding-top:8px;
           font-size:8.5pt;color:#9CA3AF;text-align:center;}}
  .amount{{font-size:13pt;font-weight:700;color:#1D4ED8;}}
  .status-paid{{color:#065F46;font-weight:700;}}
  .status-partial{{color:#92400E;font-weight:700;}}
  .status-unpaid{{color:#991B1B;font-weight:700;}}
  .section{{font-size:11pt;font-weight:700;color:#374151;
            margin:14px 0 6px 0;border-bottom:1px solid #E5E7EB;padding-bottom:4px;}}
</style></head><body>
<div class="hd">
  <h1>{school}</h1>
  <div class="sub">{title}</div>
  <div class="sub">Printed: {now}</div>
</div>
{body}
<div class="footer">Generated by School MIS</div>
</body></html>"""


def _show_preview(parent, title: str, html: str):
    doc = QTextDocument()
    doc.setHtml(html)
    printer = QPrinter(QPrinter.PrinterMode.HighResolution)
    printer.setPageMargins(QMarginsF(15, 15, 15, 15), QPrinter.Unit.Millimeter)
    dlg = QPrintPreviewDialog(printer, parent)
    dlg.setWindowTitle(f"Print Preview — {title}")
    dlg.resize(950, 720)
    dlg.paintRequested.connect(lambda p: doc.print(p))
    dlg.exec()


# ── Receipt ───────────────────────────────────────────────────────────────────

def print_receipt(parent, data: dict):
    """Show print-preview for a single payment receipt."""
    bal = max(data.get("balance", 0), 0)
    st  = data.get("status", "")
    st_cls = {"paid": "status-paid", "partial": "status-partial",
              "unpaid": "status-unpaid"}.get(st, "")

    body = f"""
<div class="kv"><b>Receipt No:</b> <span class="bold">{data.get('receipt_no','—')}</span></div>
<div class="kv"><b>Control No:</b> {data.get('control_number','—')}</div>
<hr class="thin">
<div class="kv"><b>Student Name:</b> {data.get('student','—')}</div>
<div class="kv"><b>Admission No:</b> {data.get('admission_no','—')}</div>
<div class="kv"><b>Class:</b> {data.get('class_name','—')}</div>
<div class="kv"><b>Fee Type:</b> {data.get('fee_name','—')}</div>
<hr class="thin">
<div class="kv"><b>Amount Paid:</b>
  <span class="amount">TZS {data.get('amount_paid',0):,.0f}</span></div>
<div class="kv"><b>Payment Method:</b> {data.get('payment_method','Cash')}</div>
<div class="kv"><b>Reference No:</b> {data.get('reference_no','') or '—'}</div>
<div class="kv"><b>Payment Date:</b> {data.get('payment_date','—')}</div>
<div class="kv"><b>Recorded By:</b> {data.get('recorded_by','—')}</div>
<hr class="thin">
<div class="kv"><b>Total Billed:</b> TZS {data.get('amount_due',0):,.0f}</div>
<div class="kv"><b>Discount/Waiver:</b> TZS {data.get('discount_amount',0):,.0f}</div>
<div class="kv"><b>Balance Remaining:</b> TZS {bal:,.0f}</div>
<div class="kv"><b>Bill Status:</b>
  <span class="{st_cls}">{st.upper()}</span></div>
"""
    html = _page_html("Payment Receipt", body)
    _show_preview(parent, "Payment Receipt", html)


# ── Generic table export ──────────────────────────────────────────────────────

def export_table(parent, title: str, columns: list, rows: list,
                 summary_html: str = ""):
    """Export any QTableWidget-style data as a printable table."""
    thead = "".join(f"<th>{c}</th>" for c in columns)
    tbody = ""
    for row in rows:
        tbody += "<tr>" + "".join(f"<td>{v}</td>" for v in row) + "</tr>"
    body = (
        (f'<div class="section">{title}</div>' if summary_html else "")
        + summary_html
        + f"<table><thead><tr>{thead}</tr></thead><tbody>{tbody}</tbody></table>"
    )
    html = _page_html(title, body)
    _show_preview(parent, title, html)


# ── Finance report ────────────────────────────────────────────────────────────

def print_finance_report(parent, year_label: str, stats: dict, rows: list):
    """rows: list of dicts with keys class_name, students, billed, collected,
             outstanding, waived, rate"""
    rate_str = stats.get("rate", "N/A")
    summary = f"""
<div class="section">Summary — {year_label}</div>
<table>
<tr>
  <th>Total Billed</th><th>Collected</th>
  <th>Outstanding</th><th>Waived</th>
  <th>Collection Rate</th><th>Exempt Students</th>
</tr>
<tr>
  <td>TZS {stats.get('billed',0):,.0f}</td>
  <td class="green">TZS {stats.get('collected',0):,.0f}</td>
  <td class="red">TZS {stats.get('outstanding',0):,.0f}</td>
  <td class="orange">TZS {stats.get('waived',0):,.0f}</td>
  <td class="bold">{rate_str}</td>
  <td>{stats.get('orphans',0)}</td>
</tr>
</table>
"""
    cols = ["Class", "Students Billed", "Billed (TZS)", "Collected (TZS)",
            "Outstanding (TZS)", "Waived (TZS)", "Rate"]
    table_rows = [
        [r["class_name"], r["students"], f"{r['billed']:,.0f}",
         f"{r['collected']:,.0f}", f"{r['outstanding']:,.0f}",
         f"{r['waived']:,.0f}", r["rate"]]
        for r in rows
    ]
    thead = "".join(f"<th>{c}</th>" for c in cols)
    tbody = "".join(
        "<tr>" + "".join(f"<td>{v}</td>" for v in row) + "</tr>"
        for row in table_rows
    )
    body = (
        summary
        + '<div class="section">Breakdown by Class</div>'
        + f"<table><thead><tr>{thead}</tr></thead><tbody>{tbody}</tbody></table>"
    )
    html = _page_html("Finance Report", body)
    _show_preview(parent, "Finance Report", html)


# ── Welfare report ────────────────────────────────────────────────────────────

def print_welfare_report(parent, stats: dict, rows: list):
    summary = f"""
<div class="section">Summary</div>
<table>
<tr>
  <th>Total Welfare</th><th>Orphans</th><th>Sponsored</th>
  <th>Full Exempt</th><th>Verified</th><th>Fees Waived</th>
</tr>
<tr>
  <td>{stats.get('total',0)}</td>
  <td class="red">{stats.get('orphans',0)}</td>
  <td class="green">{stats.get('sponsored',0)}</td>
  <td class="orange">{stats.get('full_exempt',0)}</td>
  <td>{stats.get('verified',0)}</td>
  <td class="red">TZS {stats.get('waived_val',0):,.0f}</td>
</tr>
</table>
"""
    cols = ["Student", "Adm No", "Class", "Category", "Support Type",
            "Sponsor", "Verified", "Fees Waived (TZS)"]
    table_rows = [
        [r["student"], r["admission_no"], r["class_name"],
         r["category"], r["support_type"], r["sponsor"],
         "Yes" if r["verified"] else "No", f"{r['waived_total']:,.0f}"]
        for r in rows
    ]
    thead = "".join(f"<th>{c}</th>" for c in cols)
    tbody = "".join(
        "<tr>" + "".join(f"<td>{v}</td>" for v in row) + "</tr>"
        for row in table_rows
    )
    body = (
        summary
        + '<div class="section">Welfare Student Roster</div>'
        + f"<table><thead><tr>{thead}</tr></thead><tbody>{tbody}</tbody></table>"
    )
    html = _page_html("Welfare Report", body)
    _show_preview(parent, "Welfare Report", html)


# ── Inventory report ──────────────────────────────────────────────────────────

def print_inventory_report(parent, stats: dict, rows: list):
    summary = f"""
<div class="section">Summary</div>
<table>
<tr><th>Total Items</th><th>Low Stock</th><th>Total Issued</th><th>Stock Value</th></tr>
<tr>
  <td>{stats.get('items',0)}</td>
  <td class="red">{stats.get('low',0)}</td>
  <td>{stats.get('issued',0)}</td>
  <td class="green">TZS {stats.get('value',0):,.0f}</td>
</tr>
</table>
"""
    cols = ["Item", "Category", "Unit Price", "In Stock", "Reorder",
            "Issued", "Returned", "Stock Value", "Status"]
    table_rows = [
        [r["name"], r["category"],
         f"{r['unit_price']:,.0f}", str(r["stock_qty"]),
         str(r["reorder_qty"]), str(r["issued"]), str(r["returned"]),
         f"{r['stock_qty']*r['unit_price']:,.0f}",
         "LOW STOCK" if r["stock_qty"] <= r["reorder_qty"] else "OK"]
        for r in rows
    ]
    thead = "".join(f"<th>{c}</th>" for c in cols)
    tbody = "".join(
        "<tr>" + "".join(
            f'<td{"  class=\"red\"" if v=="LOW STOCK" else ""}>{v}</td>'
            for v in row
        ) + "</tr>"
        for row in table_rows
    )
    body = (
        summary
        + '<div class="section">Stock Level by Item</div>'
        + f"<table><thead><tr>{thead}</tr></thead><tbody>{tbody}</tbody></table>"
    )
    html = _page_html("Inventory Report", body)
    _show_preview(parent, "Inventory Report", html)
